### ISSUE TITLE
Quality of Useability Improvments

### ISSUE THREAD

**Issue by junland** [alexqzd/Marlin#21]
Thanks @alexqzd for this wonderful firmware. First time 3D printing and your firmware has helped a lot.

Wanted to see if it would be possible to add some extra functionality for better usability:

* Beep or sequence of beeps for notifying operator that automated bed leveling has been completed. (Operator can disable this if they want.)
* Beep or sequence of beeps for notifying operator that pre-heating has been completed. (Operator can disable this if they want.)
* Beep or sequence of beeps for notifying operator that the print has been completed. (Operator can disable this if they want.)
* Z-Axis Cycle 3 to 4 times up and down for adding / spreading lubrication fluid to axis.

**Comment by alexqzd** [comment]
Thank you for your suggestions! 
BTW you can put an M300 command on your end gcode to make it beep at the end. 
The latest JyersUI build has support for gcode macros which could be used to automate the Z axis movement and more. I'll port those updates once I'm done with the H32 firmware

**Comment by junland** [comment]
Thanks! Closing this issue then.
